[package]
name = "binfire"
version = "0.0.0"
edition = "2021"

[dependencies]
pico-args = { version = "0.5", default-features = false }
binfire-lib = { version = "0.0", default-features = false, path = "../binfire-lib" }
regex = { version = "1.6", default-features = false, features = ["std"] }
