[package]
name = "binfire-lib"
version = "0.0.0"
edition = "2021"

[dependencies]
thiserror = { version = "1.0" }
reqwest = { version = "0.11", default-features = false, features = ["blocking", "rustls-tls-webpki-roots"] }
